name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      database:
        image: mongo:6.0.2
        ports:
          - '27017:27017'
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker containers
        run: |
          docker-compose -f ./docker-compose.yml up -d --build

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to be ready..."
          for i in {1..30}; do
            if docker exec broker_backend curl -s http://localhost:5000/health; then
              echo "Backend is ready!"
              break
            fi
            echo "Waiting for backend..."
            sleep 5
          done

      - name: Run tests
        run: |
          docker exec broker_backend npm install
          docker exec broker_backend npm test

      - name: Stop Docker containers
        run: docker-compose -f ./docker-compose.yml down
      
      - name: Install Netlify CLI
        run: npm install -g netlify-cli